{{- if and .Values.historyCollector.enabled .Values.historyCollector.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wavira.fullname" . }}-history-collector-data
  labels:
    {{- include "wavira.historyCollector.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.historyCollector.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.historyCollector.persistence.size }}
  {{- if .Values.historyCollector.persistence.storageClass }}
  storageClassName: {{ .Values.historyCollector.persistence.storageClass }}
  {{- end }}
{{- end }}

---
{{- if and .Values.mosquitto.enabled (not .Values.mosquitto.external) .Values.mosquitto.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wavira.fullname" . }}-mosquitto-data
  labels:
    {{- include "wavira.mosquitto.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mosquitto.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mosquitto.persistence.size }}
  {{- if .Values.mosquitto.persistence.storageClass }}
  storageClassName: {{ .Values.mosquitto.persistence.storageClass }}
  {{- end }}
{{- end }}
