apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wavira.fullname" . }}-secrets
  labels:
    {{- include "wavira.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.security.apiKey }}
stringData:
  API_KEY: {{ .Values.security.apiKey | quote }}
{{- else }}
data: {}
{{- end }}

{{- if and .Values.mosquitto.enabled (not .Values.mosquitto.external) .Values.mosquitto.config.passwords }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wavira.fullname" . }}-mosquitto-passwords
  labels:
    {{- include "wavira.mosquitto.labels" . | nindent 4 }}
type: Opaque
stringData:
  passwords.txt: |
    {{- .Values.mosquitto.config.passwords | nindent 4 }}
{{- end }}
