{{- if .Values.historyCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wavira.fullname" . }}-history-collector
  labels:
    {{- include "wavira.historyCollector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.historyCollector.service.type }}
  selector:
    {{- include "wavira.historyCollector.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.historyCollector.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}

---
{{- if and .Values.mosquitto.enabled (not .Values.mosquitto.external) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wavira.fullname" . }}-mosquitto
  labels:
    {{- include "wavira.mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mosquitto.service.type }}
  selector:
    {{- include "wavira.mosquitto.selectorLabels" . | nindent 4 }}
  ports:
    - name: mqtt
      port: {{ .Values.mosquitto.service.mqttPort }}
      targetPort: mqtt
      protocol: TCP
    - name: websocket
      port: {{ .Values.mosquitto.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
{{- end }}

{{- if and .Values.mosquitto.enabled (not .Values.mosquitto.external) .Values.mosquitto.nodePort.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wavira.fullname" . }}-mosquitto-external
  labels:
    {{- include "wavira.mosquitto.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "wavira.mosquitto.selectorLabels" . | nindent 4 }}
  ports:
    - name: mqtt
      port: {{ .Values.mosquitto.service.mqttPort }}
      targetPort: mqtt
      nodePort: {{ .Values.mosquitto.nodePort.mqttNodePort }}
      protocol: TCP
    - name: websocket
      port: {{ .Values.mosquitto.service.websocketPort }}
      targetPort: websocket
      nodePort: {{ .Values.mosquitto.nodePort.websocketNodePort }}
      protocol: TCP
{{- end }}
